# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def OCMockitoDef

pod 'OCMockito', '~> 5.1.0'

end

target 'DependenceInversionPrinciple' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DependenceInversionPrinciple

  target 'DependenceInversionPrincipleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMockito', '~> 5.1.0'
  end

end
